extract = 'rtime: (\d+)'
benchmarks = '*.bril'
epsilon = 0.000000001

[runs.baseline]
pipeline = [
    "bril2json",
    "\\time -f \"rtime: %R\" brili -p {args}",
]

[runs.brilirs]
pipeline = [
    "bril2json",
    "\\time -f \"rtime: %R\" brilirs -p {args}",
]

[runs.fastbril]
pipeline = [
    "bril2json",
    "\\time -f \"rtime: %R\" ../build/fastbrili -p {args}",
]
